#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=99

start_service() {
	local deviceID
	local ProductID
	local deviceSecret
	local enable

	config_load 'tuya_daemon'
	config_get deviceID device_details 'DeviceID'
	config_get productID device_details 'ProductID'
	config_get deviceSecret device_details 'DeviceSecret'
	config_get enabled enable 'enable'

	if [ "$enabled" -eq 1 ]; then
		procd_open_instance
		procd_set_param command /usr/bin/tuya_daemon -p "$productID" -d "$deviceID" -s "$deviceSecret"
		procd_set_param pidfile /var/run/tuya_daemon.pid
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "tuya_daemon"
}

reload_service() {
	stop
	start
}
